2022-03-21 11:08:23,072   DEBUG      server.py                       Инициализация парсера аргументов командной строки: ['C:/GB_GIT/gb_client-server_apps/gb_client-server_apps/lesson_2_7/server.py']
2022-03-21 11:08:23,072   DEBUG      server.py                       Аргументы успешно загружены.
2022-03-21 11:08:23,150   INFO       core.py                         Запущен сервер, порт для подключений: 7777, адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2022-03-21 11:08:37,728   INFO       core.py                         Установлено соединение с ПК ('127.0.0.1', 65478)
2022-03-21 11:08:38,242   DEBUG      core.py                         Разбор сообщения от клиента : {'action': 'presence', 'time': 1647850117.7405152, 'user': {'account_name': 'ser1', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAweRSmwqU/M7kQsKW53zZ\numt7Z1YX7hKSyk7pjaJSTQqx9tl+NKh9Znnca0aiH7/ho3xoA0VvUrzObLK/nx0S\n2xKwLuTqC02Fy+pr65Br59167FKWIZlVTmDHecAnsK/O5FnY+5iCtkvTmwweidPG\nrAdF/+U3OOdQnf9hjm+gAiEVIjHiXXvgLj15AaTpODbD3lZhyX4WjJ52MoYo7Y0V\nN/kSDWbb0ZyqL3988Zdo94BYADKkluc1tkP75yhuXyX/t6yXl6e+YMGenSrIrZ2Q\n+WVdgXIntI090Mz0IZEZdJrsmzvG+kjQNA6ISjQ3zeMnSfOcoFlONY5q/ruRoTSh\nkwIDAQAB\n-----END PUBLIC KEY-----'}}
2022-03-21 11:08:38,242   DEBUG      core.py                         Start auth process for {'account_name': 'ser1', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAweRSmwqU/M7kQsKW53zZ\numt7Z1YX7hKSyk7pjaJSTQqx9tl+NKh9Znnca0aiH7/ho3xoA0VvUrzObLK/nx0S\n2xKwLuTqC02Fy+pr65Br59167FKWIZlVTmDHecAnsK/O5FnY+5iCtkvTmwweidPG\nrAdF/+U3OOdQnf9hjm+gAiEVIjHiXXvgLj15AaTpODbD3lZhyX4WjJ52MoYo7Y0V\nN/kSDWbb0ZyqL3988Zdo94BYADKkluc1tkP75yhuXyX/t6yXl6e+YMGenSrIrZ2Q\n+WVdgXIntI090Mz0IZEZdJrsmzvG+kjQNA6ISjQ3zeMnSfOcoFlONY5q/ruRoTSh\nkwIDAQAB\n-----END PUBLIC KEY-----'}
2022-03-21 11:08:38,244   DEBUG      core.py                         Correct username, starting passwd check.
2022-03-21 11:08:38,245   DEBUG      core.py                         Auth message = {'response': 511, 'bin': '43dea13752883e9af404326083438d9555abde620674b4fac445f39c315f94d05c7f8e68b3b2fcad645b9732372e8fb4829c10b1107b396d9403cb3e2e1f36ef'}
2022-03-21 11:08:38,772   DEBUG      core.py                         Разбор сообщения от клиента : {'action': 'get_users', 'time': 1647850118.2466564, 'account_name': 'ser1'}
2022-03-21 11:08:39,276   DEBUG      core.py                         Разбор сообщения от клиента : {'action': 'get_contacts', 'time': 1647850118.7846649, 'user': 'ser1'}
2022-03-21 11:08:49,841   INFO       core.py                         Установлено соединение с ПК ('127.0.0.1', 65479)
2022-03-21 11:08:50,356   DEBUG      core.py                         Разбор сообщения от клиента : {'action': 'presence', 'time': 1647850129.8482943, 'user': {'account_name': 'ser2', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtP78tlz1D9vs+yGuVxRP\n5BJ2xY0EoUjmB5m8aLnTKjtASM3QCacMa5YbmfJz8oE8cuom5SKMe1ROfoxuV6YX\nJRMpSR12hpWbAD/+HNGkz64ge4L61kDpGEOt+jjWSFCmoriAuwzvon07oVR34wfk\no2Gmgw56Lrzp7Y+WBsrLtgXB5w56UnXWg8Y/p6stwTsQ4AJDKQPrn0SlbbnUotfA\n0j+WYirLFV04oNRcuYYXhKQBm06MsyiNBWm/EjA7XURJyHy4+7pv5cESXtYMLEti\nudxuVYB7/5/v8cCMD11R3hC77siz0itiOuBcXBNpLzhO/iGPgDyYBT2oMwia9krZ\nTwIDAQAB\n-----END PUBLIC KEY-----'}}
2022-03-21 11:08:50,356   DEBUG      core.py                         Start auth process for {'account_name': 'ser2', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtP78tlz1D9vs+yGuVxRP\n5BJ2xY0EoUjmB5m8aLnTKjtASM3QCacMa5YbmfJz8oE8cuom5SKMe1ROfoxuV6YX\nJRMpSR12hpWbAD/+HNGkz64ge4L61kDpGEOt+jjWSFCmoriAuwzvon07oVR34wfk\no2Gmgw56Lrzp7Y+WBsrLtgXB5w56UnXWg8Y/p6stwTsQ4AJDKQPrn0SlbbnUotfA\n0j+WYirLFV04oNRcuYYXhKQBm06MsyiNBWm/EjA7XURJyHy4+7pv5cESXtYMLEti\nudxuVYB7/5/v8cCMD11R3hC77siz0itiOuBcXBNpLzhO/iGPgDyYBT2oMwia9krZ\nTwIDAQAB\n-----END PUBLIC KEY-----'}
2022-03-21 11:08:50,357   DEBUG      core.py                         Correct username, starting passwd check.
2022-03-21 11:08:50,357   DEBUG      core.py                         Auth message = {'response': 511, 'bin': 'ca169ad398c6efeec28108db59b531bddfb78c0df615a622e74e590a1cc8b2991cbfce028f53625563d40b2571aa544fe40830e760f06c3524f7bb0f86865ac3'}
2022-03-21 11:08:50,886   DEBUG      core.py                         Разбор сообщения от клиента : {'action': 'get_users', 'time': 1647850130.3587005, 'account_name': 'ser2'}
2022-03-21 11:08:51,388   DEBUG      core.py                         Разбор сообщения от клиента : {'action': 'get_contacts', 'time': 1647850130.9066248, 'user': 'ser2'}
2022-03-21 11:08:53,414   DEBUG      core.py                         Разбор сообщения от клиента : {'action': 'pubkey_need', 'time': 1647850133.144758, 'account_name': 'ser1'}
2022-03-21 11:08:57,455   DEBUG      core.py                         Разбор сообщения от клиента : {'action': 'message', 'from': 'ser2', 'to': 'ser1', 'time': 1647850137.0399241, 'mess_text': 'NU/8rQMTOu/nL4bY/glCqUQWmlpOCDzO8bl8FMNugdZ0nD4zyh8T1C2LJOM65FTNOrvTFpffvtEyI1OghwH4R/xT+uppeUVxm6fE2T1+nfjRoKivtzbb1vq6ctbzo6cKLru1jJn1yCspp7264FbuxiGASwtazM1rWEQpLkaYSgMTIM1uDdLyg+AMRkSTqVrslkQdWk8JCG0AQxJ5l+5S0Rokscmis+wDynpjJ5gq+XAeQuQnsQsIrq2OdZblcAVIdEfmORFazF6e0ELD4oK/SqWhoMleTKlR/cuL9x+plEnVOu9HhzFDwWWuHeHbnuEtFadYiQqixxu9moDMY/tHTg=='}
2022-03-21 11:08:57,467   INFO       core.py                         Отправлено сообщение пользователю ser1 от пользователя ser2.
2022-03-21 11:09:02,003   DEBUG      core.py                         Разбор сообщения от клиента : {'action': 'pubkey_need', 'time': 1647850141.5836337, 'account_name': 'ser2'}
2022-03-21 11:09:08,574   DEBUG      core.py                         Разбор сообщения от клиента : {'action': 'message', 'from': 'ser1', 'to': 'ser2', 'time': 1647850148.3625157, 'mess_text': 'lqG+kIL0qcSTzleCxVRuTcH4mIqp6hQWN2PSl1P3LYTM4iv1vdnjdTF4i15e+rCVjM52PVoFtvPgcO3MSs/CV1YzXVexSAPJx6zh0ZOS8wG8/pqw0JlWR7bk+omNX+RYU2JFzpT7u1etHKHUvkiOcTvkWol6TMCjQ/slkOLCa0eGPGpQB3qjjh9p++DUxxgySIde6nu6hiDUhmxZMEIbgYhCGXkxKwZOcA2UsxpAWcAthI1Ts5HqEiTVHUaeFUB3BZiJQw+f4hOq3Zhp6o8JruP4LTBbH8ZAPU3XEKZvceSg8Nszlk8wdgQp9MlosvOmd0JXYV82Vy+w7Sf8a/R4RQ=='}
2022-03-21 11:09:08,586   INFO       core.py                         Отправлено сообщение пользователю ser2 от пользователя ser1.
2022-03-21 11:09:26,320   DEBUG      core.py                         Разбор сообщения от клиента : {'action': 'exit', 'time': 1647850165.9926891, 'account_name': 'ser1'}
2022-03-21 11:09:26,320   INFO       core.py                         Клиент ('127.0.0.1', 65478) отключился от сервера.
2022-03-21 11:09:28,347   DEBUG      core.py                         Разбор сообщения от клиента : {'action': 'exit', 'time': 1647850167.861429, 'account_name': 'ser2'}
2022-03-21 11:09:28,347   INFO       core.py                         Клиент ('127.0.0.1', 65479) отключился от сервера.
2022-03-21 11:36:25,219   DEBUG      server.py                       Инициализация парсера аргументов командной строки: ['C:/GB_GIT/gb_client-server_apps/gb_client-server_apps/lesson_2_7/server.py']
2022-03-21 11:36:25,219   DEBUG      server.py                       Аргументы успешно загружены.
2022-03-21 11:36:25,266   INFO       core.py                         Запущен сервер, порт для подключений: 7777, адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2022-03-21 11:36:41,645   INFO       core.py                         Установлено соединение с ПК ('127.0.0.1', 49426)
2022-03-21 11:36:42,150   DEBUG      core.py                         Разбор сообщения от клиента : {'action': 'presence', 'time': 1647851801.6521292, 'user': {'account_name': 'ser1', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAweRSmwqU/M7kQsKW53zZ\numt7Z1YX7hKSyk7pjaJSTQqx9tl+NKh9Znnca0aiH7/ho3xoA0VvUrzObLK/nx0S\n2xKwLuTqC02Fy+pr65Br59167FKWIZlVTmDHecAnsK/O5FnY+5iCtkvTmwweidPG\nrAdF/+U3OOdQnf9hjm+gAiEVIjHiXXvgLj15AaTpODbD3lZhyX4WjJ52MoYo7Y0V\nN/kSDWbb0ZyqL3988Zdo94BYADKkluc1tkP75yhuXyX/t6yXl6e+YMGenSrIrZ2Q\n+WVdgXIntI090Mz0IZEZdJrsmzvG+kjQNA6ISjQ3zeMnSfOcoFlONY5q/ruRoTSh\nkwIDAQAB\n-----END PUBLIC KEY-----'}}
2022-03-21 11:36:42,150   DEBUG      core.py                         Start auth process for {'account_name': 'ser1', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAweRSmwqU/M7kQsKW53zZ\numt7Z1YX7hKSyk7pjaJSTQqx9tl+NKh9Znnca0aiH7/ho3xoA0VvUrzObLK/nx0S\n2xKwLuTqC02Fy+pr65Br59167FKWIZlVTmDHecAnsK/O5FnY+5iCtkvTmwweidPG\nrAdF/+U3OOdQnf9hjm+gAiEVIjHiXXvgLj15AaTpODbD3lZhyX4WjJ52MoYo7Y0V\nN/kSDWbb0ZyqL3988Zdo94BYADKkluc1tkP75yhuXyX/t6yXl6e+YMGenSrIrZ2Q\n+WVdgXIntI090Mz0IZEZdJrsmzvG+kjQNA6ISjQ3zeMnSfOcoFlONY5q/ruRoTSh\nkwIDAQAB\n-----END PUBLIC KEY-----'}
2022-03-21 11:36:42,152   DEBUG      core.py                         Correct username, starting passwd check.
2022-03-21 11:36:42,153   DEBUG      core.py                         Auth message = {'response': 511, 'bin': '8a4d8ebeb602141848fb0bd1045623c8eafdcb67d006d1f31865d4c9a3fdd884bbacdbdc9d1667925e7972c8e9368889378403abe244080fdcb675ab3ea2be96'}
2022-03-21 11:36:42,666   DEBUG      core.py                         Разбор сообщения от клиента : {'action': 'get_users', 'time': 1647851802.1543522, 'account_name': 'ser1'}
2022-03-21 11:36:43,180   DEBUG      core.py                         Разбор сообщения от клиента : {'action': 'get_contacts', 'time': 1647851802.681607, 'user': 'ser1'}
2022-03-21 11:36:45,218   DEBUG      core.py                         Разбор сообщения от клиента : {'action': 'exit', 'time': 1647851805.0108023, 'account_name': 'ser1'}
2022-03-21 11:36:45,218   INFO       core.py                         Клиент ('127.0.0.1', 49426) отключился от сервера.
2022-03-21 11:51:21,356   DEBUG      server.py                       Инициализация парсера аргументов командной строки: ['C:/GB_GIT/gb_client-server_apps/gb_client-server_apps/lesson_2_7/server.py']
2022-03-21 11:51:21,356   DEBUG      server.py                       Аргументы успешно загружены.
2022-03-21 11:51:21,394   INFO       core.py                         Запущен сервер, порт для подключений: 7777, адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2022-03-21 11:51:36,248   INFO       core.py                         Установлено соединение с ПК ('127.0.0.1', 49506)
2022-03-21 11:51:36,755   DEBUG      core.py                         Разбор сообщения от клиента : {'action': 'presence', 'time': 1647852696.2569807, 'user': {'account_name': 'ser1', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAweRSmwqU/M7kQsKW53zZ\numt7Z1YX7hKSyk7pjaJSTQqx9tl+NKh9Znnca0aiH7/ho3xoA0VvUrzObLK/nx0S\n2xKwLuTqC02Fy+pr65Br59167FKWIZlVTmDHecAnsK/O5FnY+5iCtkvTmwweidPG\nrAdF/+U3OOdQnf9hjm+gAiEVIjHiXXvgLj15AaTpODbD3lZhyX4WjJ52MoYo7Y0V\nN/kSDWbb0ZyqL3988Zdo94BYADKkluc1tkP75yhuXyX/t6yXl6e+YMGenSrIrZ2Q\n+WVdgXIntI090Mz0IZEZdJrsmzvG+kjQNA6ISjQ3zeMnSfOcoFlONY5q/ruRoTSh\nkwIDAQAB\n-----END PUBLIC KEY-----'}}
2022-03-21 11:51:36,755   DEBUG      core.py                         Start auth process for {'account_name': 'ser1', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAweRSmwqU/M7kQsKW53zZ\numt7Z1YX7hKSyk7pjaJSTQqx9tl+NKh9Znnca0aiH7/ho3xoA0VvUrzObLK/nx0S\n2xKwLuTqC02Fy+pr65Br59167FKWIZlVTmDHecAnsK/O5FnY+5iCtkvTmwweidPG\nrAdF/+U3OOdQnf9hjm+gAiEVIjHiXXvgLj15AaTpODbD3lZhyX4WjJ52MoYo7Y0V\nN/kSDWbb0ZyqL3988Zdo94BYADKkluc1tkP75yhuXyX/t6yXl6e+YMGenSrIrZ2Q\n+WVdgXIntI090Mz0IZEZdJrsmzvG+kjQNA6ISjQ3zeMnSfOcoFlONY5q/ruRoTSh\nkwIDAQAB\n-----END PUBLIC KEY-----'}
2022-03-21 11:51:36,759   DEBUG      core.py                         Correct username, starting passwd check.
2022-03-21 11:51:36,760   DEBUG      core.py                         Auth message = {'response': 511, 'bin': '6425e899a1edee1d2b8f708ce4b30500866cf9b88752272d0b4a21af41a29e8409f69f4eca5b3ddba49ebe9d0ab0d9ca44405afa92d1ab5048124668dbd9d1ba'}
2022-03-21 11:51:37,268   DEBUG      core.py                         Разбор сообщения от клиента : {'action': 'get_users', 'time': 1647852696.76123, 'account_name': 'ser1'}
2022-03-21 11:51:37,771   DEBUG      core.py                         Разбор сообщения от клиента : {'action': 'get_contacts', 'time': 1647852697.278937, 'user': 'ser1'}
2022-03-21 11:51:50,940   INFO       core.py                         Установлено соединение с ПК ('127.0.0.1', 49513)
2022-03-21 11:51:51,447   DEBUG      core.py                         Разбор сообщения от клиента : {'action': 'presence', 'time': 1647852710.9461122, 'user': {'account_name': 'ser2', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtP78tlz1D9vs+yGuVxRP\n5BJ2xY0EoUjmB5m8aLnTKjtASM3QCacMa5YbmfJz8oE8cuom5SKMe1ROfoxuV6YX\nJRMpSR12hpWbAD/+HNGkz64ge4L61kDpGEOt+jjWSFCmoriAuwzvon07oVR34wfk\no2Gmgw56Lrzp7Y+WBsrLtgXB5w56UnXWg8Y/p6stwTsQ4AJDKQPrn0SlbbnUotfA\n0j+WYirLFV04oNRcuYYXhKQBm06MsyiNBWm/EjA7XURJyHy4+7pv5cESXtYMLEti\nudxuVYB7/5/v8cCMD11R3hC77siz0itiOuBcXBNpLzhO/iGPgDyYBT2oMwia9krZ\nTwIDAQAB\n-----END PUBLIC KEY-----'}}
2022-03-21 11:51:51,447   DEBUG      core.py                         Start auth process for {'account_name': 'ser2', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtP78tlz1D9vs+yGuVxRP\n5BJ2xY0EoUjmB5m8aLnTKjtASM3QCacMa5YbmfJz8oE8cuom5SKMe1ROfoxuV6YX\nJRMpSR12hpWbAD/+HNGkz64ge4L61kDpGEOt+jjWSFCmoriAuwzvon07oVR34wfk\no2Gmgw56Lrzp7Y+WBsrLtgXB5w56UnXWg8Y/p6stwTsQ4AJDKQPrn0SlbbnUotfA\n0j+WYirLFV04oNRcuYYXhKQBm06MsyiNBWm/EjA7XURJyHy4+7pv5cESXtYMLEti\nudxuVYB7/5/v8cCMD11R3hC77siz0itiOuBcXBNpLzhO/iGPgDyYBT2oMwia9krZ\nTwIDAQAB\n-----END PUBLIC KEY-----'}
2022-03-21 11:51:51,448   DEBUG      core.py                         Correct username, starting passwd check.
2022-03-21 11:51:51,448   DEBUG      core.py                         Auth message = {'response': 511, 'bin': 'f08ae2ef8e6fba656f2673f0e341758e3df4f74a1815ea0ce152a7e41531dce6c8dc02d95c48a2b87f863e1dd3234afce88bccc831ea0fd36573e9a972cd0958'}
2022-03-21 11:51:51,966   DEBUG      core.py                         Разбор сообщения от клиента : {'action': 'get_users', 'time': 1647852711.4492865, 'account_name': 'ser2'}
2022-03-21 11:51:52,469   DEBUG      core.py                         Разбор сообщения от клиента : {'action': 'get_contacts', 'time': 1647852711.9801233, 'user': 'ser2'}
2022-03-21 11:51:54,499   DEBUG      core.py                         Разбор сообщения от клиента : {'action': 'pubkey_need', 'time': 1647852714.358179, 'account_name': 'ser1'}
2022-03-21 11:51:58,045   DEBUG      core.py                         Разбор сообщения от клиента : {'action': 'pubkey_need', 'time': 1647852717.9194138, 'account_name': 'ser2'}
2022-03-21 11:52:02,109   DEBUG      core.py                         Разбор сообщения от клиента : {'action': 'message', 'from': 'ser1', 'to': 'ser2', 'time': 1647852721.7092187, 'mess_text': 'Hb8RsSa8hoSQtN2VL+ML1NaXErd20GBPppukeoWzodOxjj8C+V9qBs4r4DzXm7OwUaXfGC3gfuoexOekMe0mKScWsZNpuBf1G2GTpOGdM8X/u/58vkPM1DDxp4cb0bPcEAuR28Pa1Mij6D1W1f4Ja691s7jUhPCG5fRLl+l/ooCT0//xPGZR7a/C3XW3pP5LjkKbIhYvuANhwNZ3TvtkcWlZDD168J/mypaOin6RaoEF/2Jkwrz/pfNRw1spOE1yrWSZNgb5Z2XCFjsSie5zuIqWozA7UUzUQdcK1k28G0yVzQW6dZi4Wl6Mw5XFXWgR6hXBV2MEJ+hjIPPhATLglg=='}
2022-03-21 11:52:02,124   INFO       core.py                         Отправлено сообщение пользователю ser2 от пользователя ser1.
2022-03-21 11:52:07,705   DEBUG      core.py                         Разбор сообщения от клиента : {'action': 'exit', 'time': 1647852727.2335165, 'account_name': 'ser2'}
2022-03-21 11:52:07,705   INFO       core.py                         Клиент ('127.0.0.1', 49513) отключился от сервера.
